services:
  db:
    image: postgres
    container_name: reservation_manager
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kapi2000
      POSTGRES_DB: reservation_manager
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel_reservation_app
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/reservation_manager
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: kapi2000